namespace AxisApp.Services;

/// <summary>Precomputed accent-color values for each AccentPreset — the ~35 keys in Colors.xaml
/// that derive from the app's Primary/Secondary accent (see ThemeService's remarks). Generated
/// once from a fixed formula (not recomputed at runtime): Hover = base lightness +0.06, Pressed =
/// base lightness -0.10 with saturation x0.70, Disabled/Outline/Focus variants at fixed
/// lightness/saturation targets matching the app's original hand-tuned blue/amber values, and
/// on-accent text (TextOnAccent/CheckboxCheckmark/BadgeText) chosen per-color by WCAG contrast
/// against #08101F (dark) vs. #F2F5FA (light) — Purple and Navy are dark enough to need the light
/// variant, every other base color passes with the dark one. Secondary is a ~170deg hue rotation
/// off Primary (the same relationship the original #3D6BFF/#F2A93C pair already had), slightly
/// desaturated and darkened, then run through the same Hover/Pressed/Disabled formula.</summary>
internal static class AccentPalettes
{
    private static readonly Dictionary<AccentPreset, Dictionary<string, string>> Hex = new()
    {
        [AccentPreset.Blue] = new()
        {
            ["Primary"] = "#5B72D6",
            ["PrimaryHover"] = "#7387DC",
            ["BtnPrimary"] = "#5B72D6",
            ["BtnPrimaryHover"] = "#7387DC",
            ["BtnPrimaryPressed"] = "#4A5EB4",
            ["BtnPrimaryDisabledBg"] = "#232A48",
            ["BtnPrimaryDisabledText"] = "#7981A4",
            ["BtnPrimaryDisabledBorder"] = "#30385A",
            ["BtnOutlinePrimaryBorder"] = "#3B4987",
            ["SwitchTrackOn"] = "#5B72D6",
            ["CheckboxChecked"] = "#5B72D6",
            ["CheckboxHover"] = "#7387DC",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#5B72D6",
            ["InputCursor"] = "#5B72D6",
            ["BorderAccent"] = "#3B4987",
            ["Focus"] = "#B1BCEC",
            ["ProgressFill"] = "#5B72D6",
            ["LoaderPrimary"] = "#5B72D6",
            ["SliderThumb"] = "#5B72D6",
            ["SliderTrackActive"] = "#5B72D6",
            ["StepperIcon"] = "#5B72D6",
            ["NavItemActive"] = "#5B72D6",
            ["TabIndicator"] = "#5B72D6",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#CBA257",
            ["BtnSecondary"] = "#CBA257",
            ["BtnSecondaryHover"] = "#D2AF6E",
            ["BtnSecondaryPressed"] = "#A4844B",
            ["BtnSecondaryDisabledBg"] = "#483B23",
            ["BtnSecondaryDisabledText"] = "#A49579",
            ["BtnSecondaryDisabledBorder"] = "#5A4B30",
            ["BtnOutlineSecondaryBorder"] = "#876C3B",
            ["BadgePrimary"] = "#CBA257",
            ["BadgeText"] = "#08101F",
        },
        [AccentPreset.Green] = new()
        {
            ["Primary"] = "#4C8F63",
            ["PrimaryHover"] = "#57A371",
            ["BtnPrimary"] = "#4C8F63",
            ["BtnPrimaryHover"] = "#57A371",
            ["BtnPrimaryPressed"] = "#42664E",
            ["BtnPrimaryDisabledBg"] = "#234830",
            ["BtnPrimaryDisabledText"] = "#79A488",
            ["BtnPrimaryDisabledBorder"] = "#305A3E",
            ["BtnOutlinePrimaryBorder"] = "#3B8755",
            ["SwitchTrackOn"] = "#4C8F63",
            ["CheckboxChecked"] = "#4C8F63",
            ["CheckboxHover"] = "#57A371",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#4C8F63",
            ["InputCursor"] = "#4C8F63",
            ["BorderAccent"] = "#3B8755",
            ["Focus"] = "#C0DDCA",
            ["ProgressFill"] = "#4C8F63",
            ["LoaderPrimary"] = "#4C8F63",
            ["SliderThumb"] = "#4C8F63",
            ["SliderTrackActive"] = "#4C8F63",
            ["StepperIcon"] = "#4C8F63",
            ["NavItemActive"] = "#4C8F63",
            ["TabIndicator"] = "#4C8F63",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#814B77",
            ["BtnSecondary"] = "#814B77",
            ["BtnSecondaryHover"] = "#945689",
            ["BtnSecondaryPressed"] = "#5B3E55",
            ["BtnSecondaryDisabledBg"] = "#482341",
            ["BtnSecondaryDisabledText"] = "#A4799C",
            ["BtnSecondaryDisabledBorder"] = "#5A3052",
            ["BtnOutlineSecondaryBorder"] = "#873B79",
            ["BadgePrimary"] = "#814B77",
            ["BadgeText"] = "#F2F5FA",
        },
        [AccentPreset.Red] = new()
        {
            ["Primary"] = "#C25450",
            ["PrimaryHover"] = "#CA6A67",
            ["BtnPrimary"] = "#C25450",
            ["BtnPrimaryHover"] = "#CA6A67",
            ["BtnPrimaryPressed"] = "#954C4A",
            ["BtnPrimaryDisabledBg"] = "#482523",
            ["BtnPrimaryDisabledText"] = "#A47B79",
            ["BtnPrimaryDisabledBorder"] = "#5A3230",
            ["BtnOutlinePrimaryBorder"] = "#873E3B",
            ["SwitchTrackOn"] = "#C25450",
            ["CheckboxChecked"] = "#C25450",
            ["CheckboxHover"] = "#CA6A67",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#C25450",
            ["InputCursor"] = "#C25450",
            ["BorderAccent"] = "#873E3B",
            ["Focus"] = "#E6B9B7",
            ["ProgressFill"] = "#C25450",
            ["LoaderPrimary"] = "#C25450",
            ["SliderThumb"] = "#C25450",
            ["SliderTrackActive"] = "#C25450",
            ["StepperIcon"] = "#C25450",
            ["NavItemActive"] = "#C25450",
            ["TabIndicator"] = "#C25450",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#4CB6A8",
            ["BtnSecondary"] = "#4CB6A8",
            ["BtnSecondaryHover"] = "#62BFB3",
            ["BtnSecondaryPressed"] = "#49867E",
            ["BtnSecondaryDisabledBg"] = "#234843",
            ["BtnSecondaryDisabledText"] = "#79A49E",
            ["BtnSecondaryDisabledBorder"] = "#305A54",
            ["BtnOutlineSecondaryBorder"] = "#3B877D",
            ["BadgePrimary"] = "#4CB6A8",
            ["BadgeText"] = "#08101F",
        },
        [AccentPreset.Purple] = new()
        {
            ["Primary"] = "#7C5FBF",
            ["PrimaryHover"] = "#8E75C8",
            ["BtnPrimary"] = "#7C5FBF",
            ["BtnPrimaryHover"] = "#8E75C8",
            ["BtnPrimaryPressed"] = "#685299",
            ["BtnPrimaryDisabledBg"] = "#2E2348",
            ["BtnPrimaryDisabledText"] = "#8679A4",
            ["BtnPrimaryDisabledBorder"] = "#3D305A",
            ["BtnOutlinePrimaryBorder"] = "#523B87",
            ["SwitchTrackOn"] = "#7C5FBF",
            ["CheckboxChecked"] = "#7C5FBF",
            ["CheckboxHover"] = "#8E75C8",
            ["CheckboxCheckmark"] = "#F2F5FA",
            ["InputBorderFocused"] = "#7C5FBF",
            ["InputCursor"] = "#7C5FBF",
            ["BorderAccent"] = "#523B87",
            ["Focus"] = "#C6BAE3",
            ["ProgressFill"] = "#7C5FBF",
            ["LoaderPrimary"] = "#7C5FBF",
            ["SliderThumb"] = "#7C5FBF",
            ["SliderTrackActive"] = "#7C5FBF",
            ["StepperIcon"] = "#7C5FBF",
            ["NavItemActive"] = "#7C5FBF",
            ["TabIndicator"] = "#7C5FBF",
            ["TextOnAccent"] = "#F2F5FA",
            ["Secondary"] = "#A8B45A",
            ["BtnSecondary"] = "#A8B45A",
            ["BtnSecondaryHover"] = "#B3BE6F",
            ["BtnSecondaryPressed"] = "#838A51",
            ["BtnSecondaryDisabledBg"] = "#434823",
            ["BtnSecondaryDisabledText"] = "#9EA479",
            ["BtnSecondaryDisabledBorder"] = "#545A30",
            ["BtnOutlineSecondaryBorder"] = "#7D873B",
            ["BadgePrimary"] = "#A8B45A",
            ["BadgeText"] = "#08101F",
        },
        [AccentPreset.Pink] = new()
        {
            ["Primary"] = "#C15A87",
            ["PrimaryHover"] = "#C97097",
            ["BtnPrimary"] = "#C15A87",
            ["BtnPrimaryHover"] = "#C97097",
            ["BtnPrimaryPressed"] = "#994F6F",
            ["BtnPrimaryDisabledBg"] = "#482333",
            ["BtnPrimaryDisabledText"] = "#A4798C",
            ["BtnPrimaryDisabledBorder"] = "#5A3042",
            ["BtnOutlinePrimaryBorder"] = "#873B5C",
            ["SwitchTrackOn"] = "#C15A87",
            ["CheckboxChecked"] = "#C15A87",
            ["CheckboxHover"] = "#C97097",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#C15A87",
            ["InputCursor"] = "#C15A87",
            ["BorderAccent"] = "#873B5C",
            ["Focus"] = "#E5B9CC",
            ["ProgressFill"] = "#C15A87",
            ["LoaderPrimary"] = "#C15A87",
            ["SliderThumb"] = "#C15A87",
            ["SliderTrackActive"] = "#C15A87",
            ["StepperIcon"] = "#C15A87",
            ["NavItemActive"] = "#C15A87",
            ["TabIndicator"] = "#C15A87",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#56B67C",
            ["BtnSecondary"] = "#56B67C",
            ["BtnSecondaryHover"] = "#6BBF8D",
            ["BtnSecondaryPressed"] = "#4E8B66",
            ["BtnSecondaryDisabledBg"] = "#234832",
            ["BtnSecondaryDisabledText"] = "#79A48A",
            ["BtnSecondaryDisabledBorder"] = "#305A41",
            ["BtnOutlineSecondaryBorder"] = "#3B8759",
            ["BadgePrimary"] = "#56B67C",
            ["BadgeText"] = "#08101F",
        },
        [AccentPreset.Amber] = new()
        {
            ["Primary"] = "#A97A22",
            ["PrimaryHover"] = "#C28C27",
            ["BtnPrimary"] = "#A97A22",
            ["BtnPrimaryHover"] = "#C28C27",
            ["BtnPrimaryPressed"] = "#6F5729",
            ["BtnPrimaryDisabledBg"] = "#483B23",
            ["BtnPrimaryDisabledText"] = "#A49579",
            ["BtnPrimaryDisabledBorder"] = "#5A4B30",
            ["BtnOutlinePrimaryBorder"] = "#876C3B",
            ["SwitchTrackOn"] = "#A97A22",
            ["CheckboxChecked"] = "#A97A22",
            ["CheckboxHover"] = "#C28C27",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#A97A22",
            ["InputCursor"] = "#A97A22",
            ["BorderAccent"] = "#876C3B",
            ["Focus"] = "#EFD8AE",
            ["ProgressFill"] = "#A97A22",
            ["LoaderPrimary"] = "#A97A22",
            ["SliderThumb"] = "#A97A22",
            ["SliderTrackActive"] = "#A97A22",
            ["StepperIcon"] = "#A97A22",
            ["NavItemActive"] = "#A97A22",
            ["TabIndicator"] = "#A97A22",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#275F94",
            ["BtnSecondary"] = "#275F94",
            ["BtnSecondaryHover"] = "#2D6FAC",
            ["BtnSecondaryPressed"] = "#284560",
            ["BtnSecondaryDisabledBg"] = "#233648",
            ["BtnSecondaryDisabledText"] = "#798FA4",
            ["BtnSecondaryDisabledBorder"] = "#30455A",
            ["BtnOutlineSecondaryBorder"] = "#3B6287",
            ["BadgePrimary"] = "#275F94",
            ["BadgeText"] = "#F2F5FA",
        },
        [AccentPreset.Orange] = new()
        {
            ["Primary"] = "#C36B3E",
            ["PrimaryHover"] = "#CA7D55",
            ["BtnPrimary"] = "#C36B3E",
            ["BtnPrimaryHover"] = "#CA7D55",
            ["BtnPrimaryPressed"] = "#8D5B41",
            ["BtnPrimaryDisabledBg"] = "#483023",
            ["BtnPrimaryDisabledText"] = "#A48879",
            ["BtnPrimaryDisabledBorder"] = "#5A3E30",
            ["BtnOutlinePrimaryBorder"] = "#87553B",
            ["SwitchTrackOn"] = "#C36B3E",
            ["CheckboxChecked"] = "#C36B3E",
            ["CheckboxHover"] = "#CA7D55",
            ["CheckboxCheckmark"] = "#08101F",
            ["InputBorderFocused"] = "#C36B3E",
            ["InputCursor"] = "#C36B3E",
            ["BorderAccent"] = "#87553B",
            ["Focus"] = "#E8C6B5",
            ["ProgressFill"] = "#C36B3E",
            ["LoaderPrimary"] = "#C36B3E",
            ["SliderThumb"] = "#C36B3E",
            ["SliderTrackActive"] = "#C36B3E",
            ["StepperIcon"] = "#C36B3E",
            ["NavItemActive"] = "#C36B3E",
            ["TabIndicator"] = "#C36B3E",
            ["TextOnAccent"] = "#08101F",
            ["Secondary"] = "#419DB0",
            ["BtnSecondary"] = "#419DB0",
            ["BtnSecondaryHover"] = "#51ACBF",
            ["BtnSecondaryPressed"] = "#40737E",
            ["BtnSecondaryDisabledBg"] = "#234248",
            ["BtnSecondaryDisabledText"] = "#799DA4",
            ["BtnSecondaryDisabledBorder"] = "#30525A",
            ["BtnOutlineSecondaryBorder"] = "#3B7A87",
            ["BadgePrimary"] = "#419DB0",
            ["BadgeText"] = "#08101F",
        },
        [AccentPreset.Navy] = new()
        {
            ["Primary"] = "#35507D",
            ["PrimaryHover"] = "#3E5E92",
            ["BtnPrimary"] = "#35507D",
            ["BtnPrimaryHover"] = "#3E5E92",
            ["BtnPrimaryPressed"] = "#2E3B51",
            ["BtnPrimaryDisabledBg"] = "#233148",
            ["BtnPrimaryDisabledText"] = "#7989A4",
            ["BtnPrimaryDisabledBorder"] = "#30405A",
            ["BtnOutlinePrimaryBorder"] = "#3B5787",
            ["SwitchTrackOn"] = "#35507D",
            ["CheckboxChecked"] = "#35507D",
            ["CheckboxHover"] = "#3E5E92",
            ["CheckboxCheckmark"] = "#F2F5FA",
            ["InputBorderFocused"] = "#35507D",
            ["InputCursor"] = "#35507D",
            ["BorderAccent"] = "#3B5787",
            ["Focus"] = "#BBCAE2",
            ["ProgressFill"] = "#35507D",
            ["LoaderPrimary"] = "#35507D",
            ["SliderThumb"] = "#35507D",
            ["SliderTrackActive"] = "#35507D",
            ["StepperIcon"] = "#35507D",
            ["NavItemActive"] = "#35507D",
            ["TabIndicator"] = "#35507D",
            ["TextOnAccent"] = "#F2F5FA",
            ["Secondary"] = "#6E4F35",
            ["BtnSecondary"] = "#6E4F35",
            ["BtnSecondaryHover"] = "#835E3F",
            ["BtnSecondaryPressed"] = "#46372A",
            ["BtnSecondaryDisabledBg"] = "#483423",
            ["BtnSecondaryDisabledText"] = "#A48D79",
            ["BtnSecondaryDisabledBorder"] = "#5A4330",
            ["BtnOutlineSecondaryBorder"] = "#875E3B",
            ["BadgePrimary"] = "#6E4F35",
            ["BadgeText"] = "#F2F5FA",
        },
    };

    /// <summary>The base (unmixed) accent color for each preset — what Profile's swatch row
    /// renders per option, same value as that preset's "Primary" key.</summary>
    public static Color SwatchColor(AccentPreset preset) => Color.FromArgb(Hex[preset]["Primary"]);

    public static IEnumerable<(string Key, Color Color)> Values(AccentPreset preset) =>
        Hex[preset].Select(kv => (kv.Key, Color.FromArgb(kv.Value)));
}
